/*
 * MIT License
 *
 * Copyright (c) 2025 Webhead1104
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package me.webhead1104.towncraft.codegen;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.JavaFile;

import javax.lang.model.SourceVersion;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import java.util.Objects;

public interface TowncraftCodeGenerator {
    Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();

    default String toConstant(String namespace) {
        String constant = namespaceShort(namespace)
                .replaceFirst("brigadier:", "") // Not implicit, do not put into namespaceShort
                .replace(".", "_")
                .toUpperCase(Locale.ROOT);
        if (!SourceVersion.isName(constant)) {
            constant = "_" + constant;
        }
        return constant;
    }

    default String namespaceShort(String namespace) {
        return namespace.replaceFirst("minecraft:", "");
    }

    default void ensureDirectory(Path directory) throws IllegalStateException {
        Objects.requireNonNull(directory, "Directory is null");
        if (Files.isDirectory(directory)) return;
        try {
            Files.createDirectories(directory);
        } catch (IOException e) {
            throw new IllegalStateException("Failed to create folder for %s".formatted(directory), e);
        }
    }

    default void writeFiles(JavaFile... files) {
        Objects.requireNonNull(files, "File list cannot be null");
        final Path to = outputFolder();
        Objects.requireNonNull(to, "Output folder cannot be null");
        for (JavaFile javaFile : files) {
            try {
                javaFile.writeTo(to);
            } catch (IOException e) {
                throw new IllegalStateException("Failed to write all the output!", e);
            }
        }
    }

    default CodeBlock generateJavadoc(ClassName forImpl) {
        Objects.requireNonNull(forImpl, "for cannot be null");
        return CodeBlock.builder()
                .add("This class contains all the generated constants for {@link $T}\n<br>\n", forImpl)
                .add("Code autogenerated, do not edit!")
                .build();
    }

    Path outputFolder();

    default void generate() {
        throw new UnsupportedOperationException("This generator `%s` does not implement the generate method".formatted(getClass().getSimpleName()));
    }
}
