# Database credentials
databaseType: "mysql" # mysql or sqlite
sqlitePath: "plugins/Township/township.db"
mysql:
  host: localhost
  port: 3306
  databaseName: township
  username: root
  password: password

bannedTownNames:
  - "lol"
  - ""
  - ""

takenTownNames:
  - "no"