import net.kyori.indra.IndraExtension

plugins {
    id("java")
    application
}

group = "me.webhead1104"
version = "1.0-SNAPSHOT"

dependencies {
    implementation("net.minestom:data:${findProperty("minecraft_version") as String}-rv1")
    implementation("org.jetbrains:annotations:26.0.2-1")
    implementation("net.kyori:adventure-api:4.26.1")
    implementation("com.palantir.javapoet:javapoet:0.9.0")
    implementation("com.google.code.gson:gson:2.13.2")
}

extensions.configure<IndraExtension> {
    javaVersions {
        target(25)
        minimumToolchain(25)
        testWith(25)
    }
}

application {
    mainClass.set("me.webhead1104.towncraft.codegen.Generators")
}

tasks.getByName<JavaExec>("run") {
    args = listOf(rootProject.projectDir.resolve("platforms/common/src/autogenerated/java").absolutePath)
}
