plugins {
    id("java")
    application
}

group = "me.webhead1104"
version = "1.0-SNAPSHOT"

dependencies {
    implementation("net.minestom:data:${findProperty("minecraft_version") as String}-rv1")
    implementation(libs.jetbrainsAnnotations)
    implementation(libs.adventure.api)
    implementation(libs.javapoet)
    implementation(libs.gson)
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(25))
}

application {
    mainClass.set("me.webhead1104.towncraft.codegen.Generators")
}

tasks.getByName<JavaExec>("run") {
    args = listOf(rootProject.projectDir.resolve("platforms/common/src/autogenerated/java").absolutePath)
}
